[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && npx prisma generate --schema=./prisma/schema.prisma && npx nest build"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
