[build]
builder = "nixpacks"
buildCommand = "npx prisma generate --schema=./prisma/schema.prisma && npx nest build"

[deploy]
startCommand = "node dist/src/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
